### ISSUE TITLE
关于预训练多少epoch最优的问题

### ISSUE THREAD

**Issue by Evigouse** [935963004/LaBraM#11]
作者，您好！

首先非常感谢您分享如此精彩的工作。我有一个小小的困惑，恳请您能给予解答。
就是在预训练阶段是否划分了验证集进行模型预训练效果评估，如果没有验证集，单纯基于所有预训练数据，如何判断预训练达到多少epoch后停止可以得到最优的预训练模型。

祝好！

**Comment by 935963004** [comment]
从经验上来说，预训练越久效果越好。如果有充足的计算资源，可以尝试预训练久一些。

**Comment by Evigouse** [comment]
那请问是否会产生过拟合风险呢，是否可以通过判断预训练时loss的变化（当loss在多个epoch连续不变时就认为模型收敛）来提前结束预训练

**Comment by 935963004** [comment]
我认为过拟合对于预训练来说不一定是坏事，因为预训练未使用任何标签；相反地，如果预训练欠拟合，那么预训练就像做无用功。你的方法用于判断模型是否收敛，如果收敛了就结束训练来节省时间，我认为没什么问题，是个很好的想法。

**Comment by Evigouse** [comment]
非常感谢您细致的回复！
