### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Enzo2357** [935963004/LaBraM#16]

**Comment by 935963004** [comment]
推荐使用REAME中提供的微调脚本

OMP_NUM_THREADS=1 torchrun --nnodes=1 --nproc_per_node=8 run_class_finetuning.py \
        --output_dir ./checkpoints/finetune_tuab_base/ \
        --log_dir ./log/finetune_tuab_base \
        --model labram_base_patch200_200 \
        --finetune ./checkpoints/labram-base.pth \
        --weight_decay 0.05 \
        --batch_size 64 \
        --lr 5e-4 \
        --update_freq 1 \
        --warmup_epochs 5 \
        --epochs 50 \
        --layer_decay 0.65 \
        --drop_path 0.1 \
        --dist_eval \
        --save_ckpt_freq 5 \
        --disable_rel_pos_bias \
        --abs_pos_emb \
        --dataset TUAB \
        --disable_qkv_bias \
        --seed 0

**Comment by Enzo2357** [comment]
意思我将自己的数据处理成h5版本，将make_h5dataset_for_pretrain中的文件路径换掉，直接run_class_finetuning.py？
