### ISSUE TITLE
Can seeg data be preprocessed using the paper's？

### ISSUE THREAD

**Issue by pengzha0** [935963004/LaBraM#18]
Hello, our EEG data format is SEEG and we would like to ask if we can directly use the data preprocessing method of changing the paper. Thank you very much for your reply!

**Comment by 935963004** [comment]
It depends. To my knowledge, SEEG data differs from EEG data in many properties such as high sampling rate and high SNR. Moreover, SEEG data has many channels in a single electrode and sometimes perform bipolar reference. Therefore, I am not certain about the performance of directly applying LaBraM to SEEG data. Maybe some modifications are needed to adapt our method to SEEG.

**Comment by pengzha0** [comment]
Thank you very much！
