### ISSUE TITLE
Question about where you use forward_intermediate and get_intermediate_layers

### ISSUE THREAD

**Issue by bruAristimunha** [935963004/LaBraM#7]
Hi again @935963004,

I want to check if you use these two functions in any part of your code, and I would like to ask if not it would be okay to erase both functions.

https://github.com/935963004/LaBraM/blob/522da1dc87ed62cf8d1feba28116a2335f47f158/modeling_finetune.py#L399

https://github.com/935963004/LaBraM/blob/522da1dc87ed62cf8d1feba28116a2335f47f158/modeling_finetune.py#L439

**Comment by bruAristimunha** [comment]
I think this has come from dino, but I am not sure.

**Comment by 935963004** [comment]
You are right. We didn't use these two functions in current codes. In case of possible analysis of intermediate features, you can modify these functions to utilize them.

**Comment by bruAristimunha** [comment]
Okay, thank you!
