### ISSUE TITLE
作者，您好。如果我是 一个通道的脑电数据，做分类之类的，该怎么修改代码好呢。感谢。

### ISSUE THREAD

**Issue by xhl-JMT** [935963004/LaBraM#9]

**Comment by 935963004** [comment]
我们未测试过单通道脑电输入，因此无法保证单通道输入的性能。不过LaBraM理论上支持单通道脑电的输入。你可以参考run_class_finetuning.py中get_dataset函数的实现方式，修改为你自己的数据集。你可能需要做出以下修改：
1. 根据PyTorch标准的dataset类实现你的dataset；
2. 修改ch_names为你自己的脑电数据的通道名称，例如ch_names = ["FP1"]，注意通道名称字母需要全部大写；
3. 模型输入数据的形状须为(batch size, 1, time length, 200)，其中1为通道数量，time length为输入长度，单位为秒，例如一个样本长度为4秒就设置time length=4，200为1秒的数据点数量，即采样率为200Hz。

**Comment by xhl-JMT** [comment]
明白了，非常感谢！！

**Comment by upper127** [comment]
> 明白了，非常感谢！！
=
请问你已经完成了在自己数据集上运行此代码了吗？效果如何

**Comment by xhl-JMT** [comment]
> > 明白了，非常感谢！！
> > =
> > 请问你已经完成了在自己数据集上运行此代码了吗？效果如何

这个账号关联的是我不太常用的邮箱号，因此，没及时看到消息。我使用的是 其他任务的脑电数据集验证，还是有效果的，但也非未做调试就能达到SOTA；想在自己的数据集集上达到SOTA，可能得多多花点功夫。

**Comment by upper127** [comment]
> > > # 明白了，非常感谢！！
> > > 请问你已经完成了在自己数据集上运行此代码了吗？效果如何
> 
> 这个账号关联的是我不太常用的邮箱号，因此，没及时看到消息。我使用的是 其他任务的脑电数据集验证，还是有效果的，但也非未做调试就能达到SOTA；想在自己的数据集集上达到SOTA，可能得多多花点功夫。

请问你的分类正确率大概能达到多少呢，因为我也是直接在我的数据集上使用原模型进行验证并非重新训练，但是好像有一些问题

**Comment by xhl-JMT** [comment]
> > > > # 明白了，非常感谢！！
> > > > 请问你已经完成了在自己数据集上运行此代码了吗？效果如何
> > 
> > 
> > 这个账号关联的是我不太常用的邮箱号，因此，没及时看到消息。我使用的是 其他任务的脑电数据集验证，还是有效果的，但也非未做调试就能达到SOTA；想在自己的数据集集上达到SOTA，可能得多多花点功夫。
> 
> 请问你的分类正确率大概能达到多少呢，因为我也是直接在我的数据集上使用原模型进行验证并非重新训练，但是好像有一些问题

在sleep-edfx数据集上，该模型accuracy=0.78；2022年的SOTA=0.864

**Comment by upper127** [comment]
最后打印的accuracy是0.78不是0.78%吗，
Val:  [175/176]  eta: 0:00:00  loss: 0.8366 (0.7357)  accuracy: 0.7292 (0.7739) 
 balanced_accuracy: 0.7404 (0.7017)  cohen_kappa: nan (nan)  f1_weighted: 0.8075 (0.8102) 
 time: 0.0597  data: 0.0075  max mem: 1624
Val: Total time: 0:00:54 (0.3124 s / it)
* loss 0.736
Accuracy of the network on the 16833 val EEG: 0.77%
这个最后打印的accuracy好像差一个百分号

**Comment by jianghaisi** [comment]
> 我们未测试过单通道脑电输入，因此无法保证单通道输入的性能。不过LaBraM理论上支持单通道脑电的输入。你可以参考run_class_finetuning.py中get_dataset函数的实现方式，修改为你自己的数据集。你可能需要做出以下修改：
> 
> 1. 根据PyTorch标准的dataset类实现你的dataset；
> 2. 修改ch_names为你自己的脑电数据的通道名称，例如ch_names = ["FP1"]，注意通道名称字母需要全部大写；
> 3. 模型输入数据的形状须为(batch size, 1, time length, 200)，其中1为通道数量，time length为输入长度，单位为秒，例如一个样本长度为4秒就设置time length=4，200为1秒的数据点数量，即采样率为200Hz。

time length=4那么模型输出的特征是多少呢？
